# Generated by Django 5.0.6 on 2024-09-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_inventory_id_inventory_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
